import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:sizer/sizer.dart';
import '../presentation/cattle/cattle_page.dart';
import 'package:cowtrack/presentation/cattle/cattle_list_page.dart';
import 'package:cowtrack/presentation/cattle/cattle_page.dart';
// ⭐ ADD THESE TWO ⭐
import 'package:firebase_core/firebase_core.dart';
// <-- UNCOMMENTED AND REQUIRED: generated by flutterfire configure
import 'firebase_options.dart';

import '../core/app_export.dart';
import '../widgets/custom_error_widget.dart';

// Import the login-related pages
import '../widgets/Login/login_page.dart';
import '../widgets/Login/signup.dart';
import '../widgets/Login/forgotpassword.dart';

// Import your dashboard page
import '../presentation/dashboard_home/dashboard_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  bool _hasShownError = false;

  // ⭐ INITIALIZE FIREBASE (required) ⭐
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 🚨 CRITICAL: Custom error handling - DO NOT REMOVE
  ErrorWidget.builder = (FlutterErrorDetails details) {
    if (!_hasShownError) {
      _hasShownError = true;

      // Reset flag after 3 seconds to allow error widget on new screens
      Future.delayed(const Duration(seconds: 5), () {
        _hasShownError = false;
      });

      return CustomErrorWidget(
        errorDetails: details,
      );
    }
    return const SizedBox.shrink();
  };

  // 🚨 CRITICAL: Device orientation lock - DO NOT REMOVE
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Sizer(builder: (context, orientation, screenType) {
      return MaterialApp(
        title: 'cowtrack',
        theme: AppTheme.lightTheme,
        darkTheme: AppTheme.darkTheme,
        themeMode: ThemeMode.light,

        builder: (context, child) {
          return MediaQuery(
            data: MediaQuery.of(context).copyWith(
              textScaler: TextScaler.linear(1.0),
            ),
            child: child!,
          );
        },
        debugShowCheckedModeBanner: false,

        // Updated routes
        routes: {
          '/login': (context) => const LoginPage(),
          '/register': (context) => const SignupPage(),
          '/forgot': (context) => const ForgotPasswordPage(),
          '/dashboard': (context) => const DashboardScreen(),

          // ⭐ ADDED CATTLE NAVIGATION ⭐
          '/cattle-list': (context) => const CattlePage(
            cattleId: 'test-cow-1',
            cattleName: 'Bella',
          ),

          ...AppRoutes.routes,
        },



        // 🔥 Start app with login page
        initialRoute: '/login',
      );
    });
  }
}
